version: '2'
services:
  router:
    container_name: router
    image: nginx:1.15.2
    working_dir: /usr/share/nginx/html
    restart: always
    network_mode: "host"

  server-app:
    extends: node

  server-app-host-mode:
    extends: node
    network_mode: "host"



  node:
    image: node:10.9
    working_dir: /usr/share/app
    command:
      - npm
      - start
    restart: always


