version: '2'
services:
  router:
    container_name: router
    hostname: myapp
    domainname: myapp.com
    extends:
      file: ./base-compose.yml
      service: router
    environment:
      PORT: ${PORT}
    volumes:
      - ./router/config/default.conf:/etc/nginx/conf.d/default.conf
      - ./logs/router:/var/log/nginx

  server-app-custom-base:
    container_name: server-app-custom-auth
    extends:
      file: ./base-compose.yml
      service: server-app
    environment:
      PORT: 80
      APP_TARGET: ${APP_TARGET}
    networks:
      strawberry_net:
       ipv4_address: 174.17.0.100
    volumes:
      - ./server-auth:/usr/share/app

  server-app-custom-1:
    container_name: server-app-custom-1
    extends: server-app-custom-base
    networks:
      strawberry_net:
       ipv4_address: 174.17.0.200
    volumes:
      - ./server:/usr/share/app



  server-app-base:
    container_name: server-app-base
    logging:
      driver: none
    extends:
      file: ./base-compose.yml
      service: server-app-host-mode
    environment:
      PORT: 3000
    volumes:
      - ./server:/usr/share/app

  server-app-2:
    container_name: server-app-1
    extends: server-app-base
    environment:
      PORT: 4000

  server-app-3:
    container_name: server-app-2
    extends: server-app-base
    environment:
      PORT: 5000

  server-app-4:
    container_name: server-app-3
    extends: server-app-base
    environment:
      PORT: 6000

  server-app-5:
    container_name: server-app-4
    extends: server-app-base
    environment:
      PORT: 7000

  server-app-6:
    container_name: server-app-5
    extends: server-app-base
    environment:
      PORT: 8000


networks:
  strawberry_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 174.17.0.0/16
    driver_opts:
      "com.docker.network.bridge.name": "strawberry-net"

