version: '2'
services:
  server-app-auth-install:
    container_name: server-app-auth-install
    restart: 'no'
    extends:
      file: ./base-compose.yml
      service: server-app
    command:
      - npm
      - install
    volumes:
      - ./server-auth:/usr/share/app

  server-app-install:
    container_name: server-app-install
    restart: 'no'
    extends:
      file: ./base-compose.yml
      service: server-app
    command:
      - npm
      - install
    volumes:
      - ./server:/usr/share/app


