version: '2'
services:
  server-app-1:
    container_name: server-app-1
    logging:
      driver: none
    extends:
      file: ./base-compose.yml
      service: server-app-host-mode
    environment:
      PORT: 3000
    volumes:
      - ../server:/usr/share/app

  server-app-2:
    container_name: server-app-2
    extends:
      file: ./base-compose.yml
      service: server-app-host-mode
    environment:
      PORT: 4000
    volumes:
      - ../server:/usr/share/app

  server-app-3:
    container_name: server-app-3
    extends:
      file: ./base-compose.yml
      service: server-app-host-mode
    environment:
      PORT: 5000
    volumes:
      - ../server:/usr/share/app

  server-app-4:
    container_name: server-app-4
    extends:
      file: ./base-compose.yml
      service: server-app-host-mode
    environment:
      PORT: 6000
    volumes:
      - ../server:/usr/share/app

  server-app-5:
    container_name: server-app-5
    extends:
      file: ./base-compose.yml
      service: server-app-host-mode
    environment:
      PORT: 7000
    volumes:
      - ../server:/usr/share/app

  server-app-6:
    container_name: server-app-6
    extends:
      file: ./base-compose.yml
      service: server-app-host-mode
    working_dir: /usr/share/app
    environment:
      PORT: 8000
    volumes:
      - ../server:/usr/share/app

  server-app-7:
    container_name: server-app-7
    extends:
      file: ./base-compose.yml
      service: server-app
    networks:
      strawberry_net:
       ipv4_address: 174.17.0.200
    environment:
      PORT: 80
    volumes:
      - ../server:/usr/share/app


