version: '2'
services:
  router:
    container_name: router
    hostname: myapp
    domainname: myapp.com
    extends:
      file: ./base-compose.yml
      service: router
    environment:
      PORT: ${PORT}
    #logging:
    #  driver: none
    volumes:
      - ./config/default.conf:/etc/nginx/conf.d/default.conf

  server-app-1:
    container_name: server-app-1
    extends:
      file: ./base-compose.yml
      service: server-app
    environment:
      PORT: 3000
    volumes:
      - ../server:/usr/share/app


  server-app-2:
    container_name: server-app-2
    extends:
      file: ./base-compose.yml
      service: server-app
    environment:
      PORT: 4000
    volumes:
      - ../server:/usr/share/app

  server-app-3:
    container_name: server-app-3
    extends:
      file: ./base-compose.yml
      service: server-app
    environment:
      PORT: 5000
    volumes:
      - ../server:/usr/share/app

  server-app-4:
    container_name: server-app-4
    extends:
      file: ./base-compose.yml
      service: server-app
    environment:
      PORT: 6000
    volumes:
      - ../server:/usr/share/app

  server-app-5:
    container_name: server-app-5
    extends:
      file: ./base-compose.yml
      service: server-app
    environment:
      PORT: 7000
    volumes:
      - ../server:/usr/share/app

  server-app-6:
    container_name: server-app-6
    extends:
      file: ./base-compose.yml
      service: server-app
    working_dir: /usr/share/app
    environment:
      PORT: 8000
    volumes:
      - ../server:/usr/share/app

  server-app-7:
    container_name: server-app-7
    extends:
      file: ./base-compose.yml
      service: server-app
    working_dir: /usr/share/app
    environment:
      PORT: 9000
    volumes:
      - ../server:/usr/share/app



